### ISSUE TITLE
What about a contentful/contentful-management and a client service definition ?

### ISSUE THREAD

**Issue by lenybernard** [contentful/ContentfulBundle#20]
Hi,

This bundle is cool (and thank you for that ❤️ ) for read actions but as soon as we need to add create/update actions, then we have to do things manually.

Would you like a PR from me with the declaration of the management client ?

```shell
composer require contentful/contentful-management:@dev
```

Something like this:
```yaml
#parameters.yml
parameters:
    contentful_management_token: token

#app/config/services.yml
services:
    Contentful\Management\Client:
        arguments:
            $token: '%contentful_management_token%'
            $currentSpaceId: '%contentful_space%'
```
