### ISSUE TITLE
Breaks Symfony-Deployment in ScriptHandler::clearCache after following config example

### ISSUE THREAD

**Issue by b3nl** [contentful/ContentfulBundle#24]
```php
        $clients = [];
        foreach ($config['clients'] as $name => $client) {
            $clients[$name] = [
                'service' => sprintf('contentful.delivery.%s_client', $name),
                'api' => $client['preview'] ? 'PREVIEW' : 'DELIVERY',
                'space' => $client['space']
            ];
            $this->loadDeliveryClient($name, $client, $container);
            $this->loadDeliveryCacheWarmer($name, $client, $container);
        }
        $container->setParameter('contentful.clients', $clients);
```

Every client tries to fill the cache with its content types. But do we want to fill the cache with the preview client in the prod mode if one follows your configuration example?

```yaml
contentful:
  delivery:
    default_client: exampleapi
    clients:
      exampleapi:
        space: cfexampleapi
        token: b4c0n73n7fu1
      exapleapi_preview:
        space: cfexampleapi
        token: b4c0n73n7fu1
        preview: true
```
